"""W&B Inference model ids available for Red / Blue."""

INFERENCE_MODELS: tuple[str, ...] = (
    "meta-llama/Llama-3.1-8B-Instruct",
    "meta-llama/Llama-3.1-70B-Instruct",
    "meta-llama/Llama-3.3-70B-Instruct",
    "Qwen/Qwen3.8-27B",
    "Qwen/Qwen3.6-27B",
    "Qwen/Qwen3.6-35B-A3B",
    "Qwen/Qwen3.5-35B-A3B",
    "Qwen/Qwen3-30B-A3B-Instruct-2507",
    "Qwen/Qwen3-235B-A22B-Instruct-2507",
    "OpenPipe/Qwen3-14B-Instruct",
    "deepseek-ai/DeepSeek-V3.1",
    "deepseek-ai/DeepSeek-V4-Flash",
    "deepseek-ai/DeepSeek-V4-Flash-0731",
    "deepseek-ai/DeepSeek-V4-Pro",
    "deepseek-ai/DeepSeek-V4-Pro-0813",
    "openai/gpt-oss-20b",
    "openai/gpt-oss-120b",
    "nvidia/NVIDIA-Nemotron-3.5-Lightning-30B-A3B",
    "nvidia/NVIDIA-Nemotron-3-Ultra-550B-A55B",
    "zai-org/GLM-5.2",
    "zai-org/GLM-5.3-Flash",
    "moonshotai/Kimi-K2.6",
    "moonshotai/Kimi-K2.7-Code",
    "ibm-granite/granite-4.1-8b",
    "ibm-granite/granite-4.2-8b",
    "google/gemma-4-31B-it",
    "MiniMaxAI/MiniMax-M3",
    "JetBrains/Mellum2-12B-A2.5B-Instruct",
)
